package com.backend.moodmeter.config;

import lombok.Getter;

@Getter
public enum MoodMeterColor {
    ECSTATIC("황홀한"),
    ELATED("의기양양한"),
    ENTHUSIASTIC("열광하는"),
    THRILLED("짜릿한"),
    BLISSFUL("더없이 행복한"),
    EXHILARATED("아주 신나는"),
    INSPIRED("영감을 받은"),
    OPTIMISTIC("낙관적인"),
    PROUD("자랑스러운"),
    PLAYFUL("재미있는"),
    FESTIVE("흥겨운"),
    MOTIVATED("동기 부여된"),
    EXCITED("흥분한"),
    HAPPY("행복한"),
    HOPEFUL("희망찬"),
    UPBEAT("긍정적인"),
    CHEERFUL("쾌활한"),
    LIVELY("활발한"),
    FOCUSED("집중하는"),
    JOYFUL("기쁜"),
    SURPRISED("놀란"),
    HYPER("들뜬"),
    ENERGIZED("기운이 넘치는"),
    PLEASED("만족스러운"),
    PLEASANT("유쾌한"),
    //2nd
    SHOCKED("충격 받은"),
    STUNNED("망연자실한"),
    RESTLESS("안절부절 못하는"),
    ANNOYED("거슬리는"),
    PEEVED("언짢은"),
    JITTERY("초조한"),
    TENSE("신경이 날카로운"),
    NERVOUS("초조한"),
    IRRITATED("짜증나는"),
    UNEASY("마음이 불편한"),
    STRESSED("스트레스 받는"),
    FRUSTRATED("좌절한"),
    ANGRY("화난"),
    WORRIED("근심하는"),
    CONCERNED("염려하는"),
    PANICKED("공황에 빠진"),
    FURIOUS("몹시 화가 난"),
    FRIGHTENED("겁 먹은"),
    APPREHENSIVE("우려하는"),
    TROUBLED("골치 아픈"),
    ENRAGED("격분한"),
    LIVID("격노한"),
    FUMING("화가 치밀어 오른"),
    ANXIOUS("불안한"),
    REPULSED("불쾌한"),
    //3rd
    APATHETIC("냉담한"),
    BORED("지루한"),
    TIRED("피곤한"),
    FATIGUED("지친"),
    DRAINED("진이 빠진"),
    DOWN("의욕 없는"),
    SAD("슬픈"),
    DISHEARTENED("기죽은"),
    EXHAUSTED("기진맥진한"),
    SPENT("소모된"),
    DISAPPOINTED("실망스러운"),
    DISCOURAGED("낙담한"),
    LONELY("씁쓸한"),
    SULLEN("뚱한"),
    DESOLATE("고독한"),
    GLUM("침울한"),
    MOROSE("시무룩한"),
    MISERABLE("비참한"),
    DEPRESSED("우울한"),
    HOPELESS("가망 없는"),
    DISGUSTED("역겨운"),
    PESSIMISTIC("비관적인"),
    ALIENATED("소외된"),
    DESPONDENT("의기소침한"),
    DESPAIRING("절망한"),
    //4th
    FULFILLED("충만한"),
    TOUCHED("감동적인"),
    BALANCED("안정적인"),
    CAREFREE("근심 걱정 없는"),
    SERENE("안온한"),
    LOVING("다정한"),
    GRATEFUL("감사하는"),
    BLESSED("축복 받은"),
    COMFORTABLE("편한"),
    COZY("안락한"),
    CONTENT("자족하는"),
    SATISFIED("만족스러운"),
    RESTFUL("편안한"),
    PEACEFUL("평화로운"),
    TRANQUIL("고요한"),
    EASYGOING("태평한"),
    SECURE("안전한"),
    CHILL("차분한"),
    THOUGHTFUL("생각에 잠긴"),
    COMPLACENT("흐뭇한"),
    AT_EASE("속 편한"),
    CALM("평온한"),
    RELAXED("여유로운"),
    MELLOW("한가로운"),
    SLEEPY("나른한");
    private final String message;
    MoodMeterColor(String message) {
        this.message = message;
    }
}
